# Generated by Django 2.1.7 on 2019-02-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='daily_rate',
            new_name='imdb_rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='number_in_stock',
            new_name='meta_score',
        ),
    ]
